# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class LessonPlan(BaseModel):
    topic: typing.Optional[str] = None
    learningObjectives: typing.List[str]
    activities: typing.List[str]
    materials: typing.List[str]
    timeAllocation: typing.Optional[int] = None
    assessmentMethod: typing.Optional[str] = None
    differentiationStrategies: typing.List[str]
    codeExamples: typing.List[str]

class LessonPlanEvaluation(BaseModel):
    pacing: typing.Optional[typing.Union[str, str, str]] = None
    biases: typing.List[str]
    estimatedCosts: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
